### PR TITLE
added pytest and jsons for cohort load and update

### PR DESCRIPTION
**Pull request by ewartj**
# This PR does the following:

Adds pytest tests for the Cloudos functions load and create

# Test

Navigate to main cloudos folder and run the following command:

```
pytest -s -v
```

The expected output is:

```python
=========================================== test session starts ============================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0 -- /home/jonny/Python_envs/test_cloudos/bin/python3
cachedir: .pytest_cache
rootdir: /home/jonny/Documents/LIfebit/cloudos/cloudos-py
plugins: requests-mock-1.9.3
collected 12 items                                                                                         

tests/test_clos.py::test_process_job_list_output_correct_shape PASSED
tests/test_clos.py::test_process_job_list_output_correct_headers PASSED
tests/test_clos.py::test_process_job_list_df_values_equal PASSED
tests/test_clos.py::test_process_job_list_full_has_correct_columns PASSED
tests/test_clos.py::test_process_job_list_empty_json PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_load_correct_details PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_load_errors_with_fake_cohort PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_cohort_errors_with_none_cohort PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_name_and_desc PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_name_no_desc PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_desc_no_name_error PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_no_desc_no_name PASSED

============================================ 12 passed in 0.52s ============================================
```

### CODE REVIEW

**Comment by ilevantis** [comment]
When running `pytest` I get the following error:
```
ModuleNotFoundError: No module named 'mock'
```
Should `mock` be added to the requirements file?

After installing `mock` with pip I get the following error:

```


=========================================================== ERRORS ===========================================================
______________________________ ERROR collecting tests/test_cloudos/test_cohorts/test_cohort.py _______________________________
ImportError while importing test module '/Users/ilya/lifebit-repos/cloudos-py/tests/test_cloudos/test_cohorts/test_cohort.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../miniconda3/envs/cloudos-py/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cloudos/test_cohorts/test_cohort.py:9: in <module>
    from tests.functions_for_pytest import load_json_file
E   ModuleNotFoundError: No module named 'tests.functions_for_pytest'
```

**Comment by ilevantis** [comment]
New changes appear to have fixed the issues running the tests. I now get the following output:
```
============================= test session starts ==============================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/ilya/miniconda3/envs/cloudos-py/bin/python3.8
cachedir: .pytest_cache
rootdir: /Users/ilya/lifebit-repos/cloudos-py
plugins: requests-mock-1.9.3
collected 14 items

tests/test_clos.py::test_process_job_list_output_correct_shape PASSED
tests/test_clos.py::test_process_job_list_output_correct_headers PASSED
tests/test_clos.py::test_process_job_list_df_values_equal PASSED
tests/test_clos.py::test_process_job_list_full_has_correct_columns PASSED
tests/test_clos.py::test_process_job_list_empty_json PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_load_correct_details PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_load_errors_with_fake_cohort PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_cohort_errors_with_none_cohort PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_name_and_desc PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_name_no_desc PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_desc_no_name_error PASSED
tests/test_cloudos/test_cohorts/test_cohort.py::test_create_no_desc_no_name PASSED
tests/test_jobs/test_job.py::test_convert_nextflow_to_json_output_correct FAILED
tests/test_jobs/test_job.py::test_convert_nextflow_to_json_badly_formed_config FAILED

=================================== FAILURES ===================================
_________________ test_convert_nextflow_to_json_output_correct _________________

    def test_convert_nextflow_to_json_output_correct():
>       job_json = Job.convert_nextflow_to_json(
            1, param_dict["config"],
            project_id=param_dict["project_id"],
            workflow_id=param_dict["workflow_id"],
            job_name=param_dict["job_name"],
            resumable=param_dict["resumable"],
            instance_type=param_dict["instance_type"],
            instance_disk=param_dict["instance_disk"],
            spot=param_dict["spot"]
            )
E       TypeError: convert_nextflow_to_json() missing 4 required positional arguments: 'git_commit', 'git_tag', 'batch', and 'nextflow_profile'

tests/test_jobs/test_job.py:21: TypeError
______________ test_convert_nextflow_to_json_badly_formed_config _______________

    def test_convert_nextflow_to_json_badly_formed_config():
        no_equals_config = "tests/test_data/wrong_params.config"
        with pytest.raises(ValueError) as excinfo:
>           job_json = Job.convert_nextflow_to_json(
                1, no_equals_config,
                project_id=param_dict["project_id"],
                workflow_id=param_dict["workflow_id"],
                job_name=param_dict["job_name"],
                resumable=param_dict["resumable"],
                instance_type=param_dict["instance_type"],
                instance_disk=param_dict["instance_disk"],
                spot=param_dict["spot"]
                )
E           TypeError: convert_nextflow_to_json() missing 4 required positional arguments: 'git_commit', 'git_tag', 'batch', and 'nextflow_profile'

tests/test_jobs/test_job.py:39: TypeError
=========================== short test summary info ============================
FAILED tests/test_jobs/test_job.py::test_convert_nextflow_to_json_output_correct
FAILED tests/test_jobs/test_job.py::test_convert_nextflow_to_json_badly_formed_con
```

Those two tests are not in the original PR description, should we expect them to be failing?

**Comment by ilevantis** [comment]
Should `mock` be added to the requirements file or is it deliberately omitted so that users of the package that will not be carrying out tests do not need to download the package?

**Review by ilevantis — APPROVED** [review]
All tests passing for me now. LGTM 👍 .

**Comment by dapineyro** [comment]
Great PR @ewartj ! I only have the very same comments as here: https://github.com/lifebit-ai/cloudos-cli/pull/41#issuecomment-1194365189. In this case, the version should be v.0.1.2c

**Review by dapineyro — APPROVED** [review]
LGTM!

**Pull request merged**
